### ISSUE TITLE
我想展开收缩俩字在最右边

### ISSUE THREAD

**Issue by marren06** [xubinbin1024/MoreTextView#1]
![image](https://user-images.githubusercontent.com/17778482/30728637-fe174144-9f8b-11e7-9681-3121945adf47.png)
如图  始终在最右面

**Comment by binny1024** [comment]
抱歉，这个功能你已经实现了吧。上个月结婚，比较忙。没看github，我可以提个解决方案，你可以自定一个控件，用组合view的方式，一个textview 和一个图片，然后各图片加属性动画。有问题请加QQ群讨论 192268854 ，ＱＱ肯定一直都在的
